name: lrtc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - python=3.7.10
  - readline=8.1
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - astunparse==1.6.3
    - boto3==1.17.73
    - botocore==1.20.73
    - cached-property==1.5.2
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - click==8.0.0
    - cycler==0.10.0
    - dataclasses==0.6
    - dill==0.3.3
    - enum34==1.1.6
    - filelock==3.0.12
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==4.0.1
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonpickle==1.3
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.2
    - mip==1.13.0
    - multiprocess==0.70.11.1
    - nose==1.3.7
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==0.25.2
    - pandas-access==0.0.1
    - pathlib==1.0.1
    - pillow==8.2.0
    - pip==21.1.2
    - protobuf==3.17.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - regex==2021.4.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3transfer==0.4.2
    - sacremoses==0.0.45
    - scikit-learn==0.21.3
    - scipy==1.4.1
    - seaborn==0.11.0
    - sentencepiece==0.1.95
    - setuptools==57.0.0
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - tokenizers==0.5.2
    - tqdm==4.60.0
    - transformers==2.5.1
    - typing-extensions==3.7.4.3
    - ujson==3.1.0
    - urllib3==1.26.4
    - werkzeug==2.0.0
    - wrapt==1.12.1
    - wrapt-timeout-decorator==1.3.1
    - zipp==3.4.1
